name: CI

on:
  pull_request:

jobs:
  check:
    name: Check
    runs-on: macos-14

    steps:
      - uses: actions/checkout@v4

      - uses: Swatinem/rust-cache@v2

      - name: Format
        run: cargo fmt --check

      - name: Check
        run: cargo check

      - name: Clippy
        run: cargo clippy -- -D warnings

      - name: Test
        run: cargo test
